
apiVersion: well/v0.1
kind: Well
metadata:
  namespace: screen
  name: wildcat
  author: equinor

spec:

  well_header:

    well_name: 'WellA'
    well_rkb: 25
    sf_depth_msl: 300
    well_td_rkb: 1500
    sf_temp: 4
    geo_tgrad: 40

  drilling:

    - top_rkb: 325
      bottom_rkb: 720
      diameter_in: '17 1/2'

    - top_rkb: 720
      bottom_rkb: 1185
      diameter_in: '12 1/4'

    - top_rkb: 1185
      bottom_rkb: 3186
      diameter_in: '8 1/2'

  casing_cement:

    - top_rkb: 325
      bottom_rkb: 709
      diameter_in: '13 3/8'
      toc_rkb: 325
      boc_rkb: 709
      shoe: true

    - top_rkb: 622
      bottom_rkb: 1137
      diameter_in: '9 5/8'
      toc_rkb: 706
      boc_rkb: 1137.5
      shoe: true

  barriers:

    - barrier_name: cplug2
      barrier_type: cplug
      top_rkb: 400
      bottom_rkb: 550

    - barrier_name: cplug1
      barrier_type: mech_plug
      top_rkb: 1.00E+03
      bottom_rkb: 1100

  geology:

    - top_rkb: 325
      geol_unit: 'OVERBURDEN'
      reservoir_flag: false

    - top_rkb: 1200
      geol_unit: 'CAP ROCK'
      reservoir_flag: false

    - top_rkb: 1250
      geol_unit: 'RESERVOIR'
      reservoir_flag: true

    - top_rkb: 1300
      geol_unit: 'UNDERBURDEN'
      reservoir_flag: false

  reservoir_pressure:

    depth_msl: 1250
    RP2: '+ 25'
    RP3: '- 25'

  co2_datum: 1300

  main_barrier: cplug1

  barrier_permeability:
    quality: ['good', 'mid', 'poor']
    kv: [0.01, 10, 1.00E+03]
